
package com.bigguy.ws.customer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ICustomerService", targetNamespace = "http://crm.ws.bigguy.com/")
@XmlSeeAlso({
//    ObjectFactory.class
})
public interface ICustomerService {


    /**
     * 
     * @return
     *     returns java.util.List<com.bigguy.ws.customer.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findNotAssociation", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindNotAssociation")
    @ResponseWrapper(localName = "findNotAssociationResponse", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindNotAssociationResponse")
    public List<Customer> findNotAssociation();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.bigguy.ws.customer.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListAssociation", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindListAssociation")
    @ResponseWrapper(localName = "findListAssociationResponse", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindListAssociationResponse")
    public List<Customer> findListAssociation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.bigguy.ws.customer.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://crm.ws.bigguy.com/", className = "com.bigguy.ws.customer.FindAllResponse")
    public List<Customer> findAll();

}
